name: weather_flutter_app
description: "A Flutter project pour lâ€™examen L3GL ISI 2026"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ğŸ“¡ Pour rÃ©cupÃ©rer les donnÃ©es mÃ©tÃ©o depuis une API
  http: ^1.1.0

  # ğŸŸ¢ Pour afficher la jauge animÃ©e
  percent_indicator: ^4.2.2

  # ğŸ—ºï¸ Pour la carte interactive Google Maps
  google_maps_flutter: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # âš¡ï¸ Ajoute tes icÃ´nes ou images mÃ©tÃ©o ici
  assets:
    - assets/images/